console.log("solution A", getSolution1A());
console.log("solution B", getSolution1B());
function getSolution1A() {}
function getSolution1B() {}
function getSolution2A() {}
function getSolution2B() {}
function getSolution3A() {}
function getSolution3B() {}
function getSolution4A() {}
function getSolution4B() {}
function getSolution5A() {}
function getSolution5B() {}
function getSolution6A() {}
function getSolution6B() {}
function getSolution7A() {}
function getSolution7B() {}
function getSolution8A() {}
function getSolution8B() {}
function getSolution9A() {}
function getSolution9B() {}
function getSolution10A() {}
function getSolution10B() {}
function getSolution11A() {}
function getSolution11B() {}
function getSolution12A() {}
function getSolution12B() {}
function getSolution13A() {}
function getSolution13B() {}
function getSolution14A() {}
function getSolution14B() {}
function getSolution15A() {}
function getSolution15B() {}
function getSolution16A() {}
function getSolution16B() {}
function getSolution17A() {}
function getSolution17B() {}
function getSolution18A() {}
function getSolution18B() {}
function getSolution19A() {}
function getSolution19B() {}
function getSolution20A() {}
function getSolution20B() {}
function getSolution21A() {}
function getSolution21B() {}
function getSolution22A() {}
function getSolution22B() {}
function getSolution23A() {}
function getSolution23B() {}
function getSolution24A() {}
function getSolution24B() {}
function getSolution25A() {}
function getSolution25B() {}
